### PR TITLE
Setup CLI integration with Supperannotate (ie download and push)

### LINKED ISSUE #1: Setup CLI integration with Supperannotate (ie download and push)
Verify the token

### PR DESCRIPTION
**Pull request by nlauchande**
# Integration_Test

## Description

Setup CLI integration with Supperannotate (ie download and push)
Fixes #1

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by tjiagoM — COMMENTED** [review]
Given that we want to make it easier for everyone to use this, I would suggest the following change:

In README, point 3, I'd say instead "Create a config.json copied from conf.json and add the right token". And then, in the main.py you just change everything to `config.json`
I'm suggesting this because it seems to me you have your own config file with this name (and ignored in .gitignore). Therefore, I think this tweak would require less changes from everybody when cloning and updating the repo. After all, we must not update the token to the repository, therefore we will always need to change main.py to another file. So, why not make that already? :) Let me know what you think.

**Comment by nlauchande** [comment]
@tjiagoM: Your change makes sense. I Will work on it.

**Review by tjiagoM — APPROVED** [review]
lgtm ;)

**Comment by nlauchande** [comment]
@tjiagoM : I will merge this one . Will send a PR soon on the new task.

**Pull request merged**
